project:
  type: website
  output-dir: docs

website:
  title: "Kevin Scott"
  navbar:
    background: light
    collapse: false
    left:
      - href: index.qmd
        text: KS
    right:
      - href: projects.qmd
        text: Projects
      - href: blog.qmd
        text: Writing
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true



