project:
  type: website
  output-dir: .

website:
  title: "Kevin Scott - AI Systems & Performance"
  navbar:
    background: light
    collapse: false
    left:
      - text: "Kevin Scott"
        href: index.qmd
    right:
      - text: "Projects"
        href: projects.qmd
      - text: "Research" 
        href: blog.qmd
      - text: "Contact"
        href: contact.qmd

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true



